[package]
name = "chessica"
version = "0.0.0"
edition = "2021"

#[lib]
#name = "chessica"
#path = "src/main.rs"

[dependencies]
lazy_static = "1.4.0"

[profile.dev]
opt-level = 3   # Full throttle optimization

